/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio3;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
public class framefig extends javax.swing.JFrame {

    /**
     * Creates new form framefig
     */
    public framefig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cilinderbutton = new javax.swing.JButton();
        ballbutton = new javax.swing.JButton();
        cubebutton = new javax.swing.JButton();
        trianglebutton = new javax.swing.JButton();
        obamabutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cilinderbutton.setText("Cilindro");
        cilinderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cilinderbuttonActionPerformed(evt);
            }
        });

        ballbutton.setText("Esfera");
        ballbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballbuttonActionPerformed(evt);
            }
        });

        cubebutton.setText("Cubo");
        cubebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubebuttonActionPerformed(evt);
            }
        });

        trianglebutton.setText("Piramide");
        trianglebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trianglebuttonActionPerformed(evt);
            }
        });

        obamabutton.setText("Prisma Triangular");
        obamabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obamabuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione una figura geométrica:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(cilinderbutton)
                        .addGap(18, 18, 18)
                        .addComponent(ballbutton)
                        .addGap(18, 18, 18)
                        .addComponent(cubebutton)
                        .addGap(18, 18, 18)
                        .addComponent(trianglebutton)
                        .addGap(18, 18, 18)
                        .addComponent(obamabutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cilinderbutton)
                    .addComponent(ballbutton)
                    .addComponent(cubebutton)
                    .addComponent(trianglebutton)
                    .addComponent(obamabutton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cilinderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cilinderbuttonActionPerformed
        cilindroframe h=new cilindroframe();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
    }//GEN-LAST:event_cilinderbuttonActionPerformed

    private void ballbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballbuttonActionPerformed
        ballframe h=new ballframe();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
    }//GEN-LAST:event_ballbuttonActionPerformed

    private void cubebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubebuttonActionPerformed
        cubeframe h=new cubeframe();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
    }//GEN-LAST:event_cubebuttonActionPerformed

    private void trianglebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trianglebuttonActionPerformed
        triangleframe h=new triangleframe();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
    }//GEN-LAST:event_trianglebuttonActionPerformed

    private void obamabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obamabuttonActionPerformed
        obamiumframe h=new obamiumframe();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
    }//GEN-LAST:event_obamabuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framefig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framefig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framefig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framefig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framefig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ballbutton;
    private javax.swing.JButton cilinderbutton;
    private javax.swing.JButton cubebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton obamabutton;
    private javax.swing.JButton trianglebutton;
    // End of variables declaration//GEN-END:variables
}
